# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "04847e926845c853b6a67cd64caf0dc7"
name = "Review App Loox"
handle = "review-app-loox"
application_url = "https://hungarian-injured-samba-mins.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://hungarian-injured-samba-mins.trycloudflare.com/auth/callback", "https://hungarian-injured-samba-mins.trycloudflare.com/auth/shopify/callback", "https://hungarian-injured-samba-mins.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
